### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by zhouhao27** [RVC-Project/Retrieval-based-Voice-Conversion#11]
Always got this message:

> INFO:xx:Train Epoch: 478 [92%]
INFO:xx:[110200, 9.421142503636453e-05]
INFO:xx:loss_disc=3.598, loss_gen=3.174, loss_fm=8.765,loss_mel=19.367, loss_kl=1.520

Is this normal?

**Comment by Tps-F** [comment]
Yeah, that's okay.
