### ISSUE TITLE
How can I use RVC on my CPU?

### ISSUE THREAD

**Issue by alcoftTAO** [RVC-Project/Retrieval-based-Voice-Conversion#16]
I have an NVIDIA graphics card, but I don't want to use the GPU, I just want to use my CPU.
When I run my code, RVC automatically runs on my GPU.

How can I change the device?

**Comment by Tps-F** [comment]
OK, i'll support that

**Comment by alcoftTAO** [comment]
I created a pull request where I fix this by adding a variable that allows you to use the CPU or GPU for inference.
