### ISSUE TITLE
AttributeError: 'VC' object has no attribute 'vc_infer'.

### ISSUE THREAD

**Issue by codecooker1** [RVC-Project/Retrieval-based-Voice-Conversion#21]
### **Just Ctrl+C and Ctrl+V ed the code sample in README but it doesn't seem to be working**

It turns out that the code in package is not the same as this repo.
This is the command I used to install he package:
`pip install rvc`

**Comparations Below: **
This is the function `vc_infer` is used to do the infering.

![rvc github version](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion/assets/134213806/389b6f97-5df4-4795-900a-772bb12927ea)

But in the package the code looks like this. (vc_single instead of vc_infer)

![rvc package version](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion/assets/134213806/19f5035c-c9b6-438c-992b-346234bf306d)

This raises an `AttributeError` for those who follow the guide in README as there is nothing called `vc_infer` there.

**Comment by Tps-F** [comment]
Install the latest version from github, not pypi
